In [1]:
# Creating network, inicialization of parameters
# człowiek , ryba , ptak

import pandas as pd
import numpy as np
from Siec_plytka.init import init1
from Siec_plytka.dzialaj1 import calculate1, calculate2
from Siec_plytka.ucz1 import ucz1

examples = pd.read_csv('dane_uczace.csv')
examples = np.array(examples)

x_train = examples[:, :5]
y_train = examples[:, 5:]
print(x_train)
print(y_train)



[[ 4.    0.01  0.01 -1.   -1.5 ]
 [ 2.   -1.    2.    2.5   2.  ]
 [-1.    3.5   0.01 -2.    1.5 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
W_matrix = init1(5,3)  # 5 numbers in input, 3 neurons in layer1 (3 outputs)
print("Tak wyglądają zainicjalizowane wagi")
print(f"Wagi początkowe:\n {W_matrix}")
#result1 = calculate1(W_matrix, x_train[0])
#print(calculate1(W_matrix,x_train))

W_optimal = ucz1(W_matrix, x_train, y_train, 1000)

print(f"Wagi wytrenowane:\n {W_optimal}")

print("---------------------------------")
print("Teraz przewiduję:")
print(f"W optimal:\n {W_optimal}")
print(f"x_train:\n  {x_train}")
przewidywania = calculate2(W_optimal, x_train)
print(przewidywania)

print("---------------------------------")
print("x_test")
x_test = np.array([[2,0.2,0.3,0.1,0.05]])

przewidywania = calculate2(W_optimal, x_test)
print(przewidywania)

Tak wyglądają zainicjalizowane wagi
Wagi początkowe:
 [[ 0.09633676  0.08027266 -0.01991573  0.0030517   0.02890641]
 [ 0.05039148  0.03789566  0.06743146  0.07586847 -0.08307292]
 [-0.01659014 -0.0880497  -0.05415032 -0.01820543  0.06358113]]
Wagi wytrenowane:
 [[0.81329757 0.79723347 0.69704508 0.72001251 0.74586722]
 [0.25579466 0.24329884 0.27283464 0.28127165 0.12233026]
 [0.79633255 0.724873   0.75877238 0.79471727 0.87650383]]
---------------------------------
Teraz przewiduję:
W optimal:
 [[0.81329757 0.79723347 0.69704508 0.72001251 0.74586722]
 [0.25579466 0.24329884 0.27283464 0.28127165 0.12233026]
 [0.79633255 0.724873   0.75877238 0.79471727 0.87650383]]
x_train:
  [[ 4.    0.01  0.01 -1.   -1.5 ]
 [ 2.   -1.    2.    2.5   2.  ]
 [-1.    3.5   0.01 -2.    1.5 ]]
[ 4.    0.01  0.01 -1.   -1.5 ]
TEST: [1.42931972 0.56357295 1.09069365] 
pochodne: [0.0039315  0.26594613 0.02122501]
TEST: [5.51521753 1.76179941 6.12513771] 
pochodne: [5.28244115e-12 7.46691921e-04 2.49800181