In [1]:
# Creating network, inicialization of parameters
# człowiek , ryba , ptak

import pandas as pd
import numpy as np
from Siec_plytka.init import init1
from Siec_plytka.dzialaj1 import calculate1
from Siec_plytka.ucz1 import ucz1

examples = pd.read_csv('dane_uczace.csv')
examples = np.array(examples)

x_train = examples[:, :5].T
y_train = examples[:, 5:]
print(x_train)
print(y_train)


[[ 4.    2.   -1.  ]
 [ 0.01 -1.    3.5 ]
 [ 0.01  2.    0.01]
 [-1.    2.5  -2.  ]
 [-1.5   2.    1.5 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
W_matrix = init1(5,3)  # 5 numbers in input, 3 neurons in layer1 (3 outputs)
print(W_matrix)
#result1 = calculate1(W_matrix, x_train[0])
print(calculate1(W_matrix,x_train))

W_optimal = ucz1(W_matrix, x_train, y_train, 10)
print(W_optimal)
print(calculate1(W_optimal,x_train))



[[-0.03235869 -0.0145582   0.09436552  0.05716442 -0.01039387]
 [ 0.0434993  -0.09361154  0.02784976  0.00966184  0.04880119]
 [-0.03005568  0.08517407  0.03111865 -0.0201854   0.09244069]]
[[1.04842155 0.83981968 1.09419174]
 [1.18816735 0.61286879 0.70583154]
 [0.89535397 1.22960857 0.33949919]]
(array([[0.29921232, 0.78641939, 0.32347337],
       [0.6112049 , 0.85696813, 0.17010048],
       [0.23367462, 0.56386146, 0.92673195]]), array([[1.04842155, 0.83981968, 1.09419174],
       [1.18816735, 0.61286879, 0.70583154],
       [0.89535397, 1.22960857, 0.33949919]]))
liczba cech wejściowych ucz1: 3 


ValueError: shapes (3,5) and (3,) not aligned: 5 (dim 1) != 3 (dim 0)