In [1]:
# Creating network, inicialization of parameters
# człowiek , ryba , ptak

import pandas as pd
import numpy as np
from Siec_plytka.init import init1
from Siec_plytka.dzialaj1 import calculate1, calculate2
from Siec_plytka.ucz1 import ucz1

examples = pd.read_csv('dane_uczace.csv')
examples = np.array(examples)

x_train = examples[:, :5]
y_train = examples[:, 5:]
print("Dane treningowe")
print(x_train)
print("Etykiety treningowe")
print(y_train)



Dane treningowe
[[ 4.    0.01  0.01 -1.   -1.5 ]
 [ 2.   -1.    2.    2.5   2.  ]
 [-1.    3.5   0.01 -2.    1.5 ]]
Etykiety treningowe
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
W_matrix = init1(5,3)  # 5 numbers in input, 3 neurons in layer1 (3 outputs)
print("Tak wyglądają zainicjalizowane wagi")
print(f"Wagi początkowe:\n {W_matrix}")
print(W_matrix.shape)

Tak wyglądają zainicjalizowane wagi
Wagi początkowe:
 [[-0.08162906  0.05229272  0.01960534 -0.05732764 -0.03195658]
 [-0.04667525  0.07471429 -0.0309389   0.05056037 -0.00673646]
 [ 0.02384518 -0.04139417  0.09077945  0.0232007  -0.0547473 ]]
(3, 5)


In [5]:
outputs_sigmoid = calculate1(W_matrix, x_train[0])
print(outputs_sigmoid)

[0.24923926 0.24349832 0.68437994]


In [6]:

#result1 = calculate1(W_matrix, x_train[0])
#print(calculate1(W_matrix,x_train))
print(f"x_train transpose: \n{np.transpose(x_train[0])} ")

W_optimal = ucz1(W_matrix, x_train, y_train, 1000)
print("###############################################")
print(f"Wagi wytrenowane:\n {W_optimal}")


x_train transpose: 
[ 4.    0.01  0.01 -1.   -1.5 ] 
result [0.12810016 0.35776614 0.74946349]
cost: [-0.12810016  0.64223386 -0.74946349]
TESTY
0.1
[[-0.08162906  0.05229272  0.01960534 -0.05732764 -0.03195658]
 [-0.04667525  0.07471429 -0.0309389   0.05056037 -0.00673646]
 [ 0.02384518 -0.04139417  0.09077945  0.0232007  -0.0547473 ]]
Koniec TESTOW
OBLICZANIE dj_dW:
expamples[random_sample]: [ 2.  -1.   2.   2.5  2. ]
derivative: [-0.07153786  0.73782886 -0.70362618]
Koniec
dj_dW: [[-0.01430757  0.00715379 -0.01430757 -0.01788447 -0.01430757]
 [ 0.14756577 -0.07378289  0.14756577  0.18445721  0.14756577]
 [-0.14072524  0.07036262 -0.14072524 -0.17590655 -0.14072524]]
result [0.8727396  0.14476337 0.75948629]
cost: [-0.8727396  -0.14476337  0.24051371]
TESTY
0.1
[[-0.09593663  0.0594465   0.00529777 -0.07521211 -0.04626415]
 [ 0.10089052  0.0009314   0.11662687  0.23501758  0.14082931]
 [-0.11688006  0.02896845 -0.04994579 -0.15270584 -0.19547254]]
Koniec TESTOW
OBLICZANIE dj_dW:
expa

In [8]:
print("---------------------------------")
print("Teraz przewiduję:")
# print(f"W optimal:\n {W_optimal}")
# print(f"x_train:\n  {x_train}")
# przewidywania = calculate2(W_optimal, x_train)
# print(przewidywania)


outputs_sigmoid = calculate1(W_optimal, x_train[0])
print(outputs_sigmoid)
outputs_sigmoid = calculate1(W_optimal, x_train[1])
print(outputs_sigmoid)
outputs_sigmoid = calculate1(W_optimal, x_train[2])
print(outputs_sigmoid)


---------------------------------
Teraz przewiduję:
[0.99809314 0.00422565 0.00443357]
[5.10980986e-03 9.99461156e-01 5.55957520e-04]
[0.00607743 0.00575402 0.99510145]


In [11]:
print("---------------------------------")
x_test = np.array([2, 0.2, 0.3, 0.1, 0.05])

przewidywania= calculate1(W_optimal, x_test)
print(przewidywania)

---------------------------------
[0.66342136 0.29529617 0.03071257]
